name: Ubuntu SSH

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Enter hostname'
        default: 'ubuntu'
        required: false
        type: string
      username:
        description: 'Enter username'
        default: 'user'
        required: false
        type: string
      password:
        description: 'Enter password'
        default: 'root'
        required: false
        type: string
      ngrok_token:
        description: 'Enter authtoken'
        required: false
        type: string
      ngrok_region:
        description: 'Enter region'
        default: 'us'
        required: false
        type: string

jobs:
  deploy_SSH_server:
    name: Deploy an SSH server
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up ngrok
      run: |
        echo "Downloading ngrok..."
        curl -fsSL https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip -q ngrok.zip -d /usr/local/bin
        rm ngrok.zip
        chmod +x /usr/local/bin/ngrok
        echo "ngrok version:"
        ngrok version

    - name: Configuring an SSH server...
      run: bash Ubuntu_SSH.sh

    - name: Starting ngrok SSH tunnel
      run: |
        echo "Starting ngrok tunnel for SSH..."
        screen -dmS ngrok ngrok tcp 22 --authtoken ${{ inputs.ngrok_token }} --region ${{ inputs.ngrok_region }}

    - name: Keeping runner active...
      run: bash Keep_Alive.sh
