name: Ubuntu SSH

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Enter hostname'
        default: 'ubuntu'
        required: false
        type: string
      username:
        description: 'Enter username'
        default: 'user'
        required: false
        type: string
      password:
        description: 'Enter password'
        default: 'root'
        required: false
        type: string
      ngrok_token:
        description: 'Enter authtoken'
        required: true
        type: string
      ngrok_region:
        description: 'Enter region'
        default: 'us'
        required: false
        type: string

jobs:
  deploy_SSH_server:
    name: Deploy an SSH server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove old ngrok if exists
      run: sudo rm -f /usr/local/bin/ngrok

    - name: Download and install ngrok v3.2.0
      run: |
        curl -fsSL https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip -q ngrok.zip -d /usr/local/bin
        rm ngrok.zip
        chmod +x /usr/local/bin/ngrok

    - name: Verify ngrok installation
      run: ngrok version

    - name: Configure SSH server and ngrok
      run: |
        bash ./Ubuntu_SSH.sh
      env:
        hostname: ${{ inputs.hostname }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        ngrok_token: ${{ inputs.ngrok_token }}
        ngrok_region: ${{ inputs.ngrok_region }}

    - name: Keeping runner active
      run: bash Keep_Alive.sh
